import { inject, Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpHeaders } from '@angular/common/http';
import { catchError, delay, map, Observable, of, retryWhen, take, tap, throwError } from 'rxjs';
import { Donut } from '../models/donut.model';

@Injectable()
export class DonutService {
  private donuts: Donut[] = [];
  private http: HttpClient = inject(HttpClient);

  getDonuts(): Observable<Donut[]> {
    // If there's already data can just return 
    // the loaded donuts list instead of recalling http request.
    if(this.donuts.length) {
      return of(this.donuts);
    }

    let headers = new HttpHeaders({
      'Content-Type': 'application/json'
    });
    
    headers = headers.append('Api-Token', '1234abcd');

    const options = { headers };

    return this.http.get<Donut[]>(`/api/donuts`, options)
      .pipe(
        tap(donuts => this.donuts = donuts),
        retryWhen((errors) => errors.pipe(delay(1000), take(2))),
        catchError(this.handleError)
      );
  }

  getDonut(id: string | null): Observable<Donut> {
    return this.getDonuts()
      .pipe(
        map(donuts => {
          const donut = donuts.find(donut => donut.id === id);
          return donut ? donut : {name: '', icon: '', price: 0, description: ''};   
        })
      );
  }

  createDonut(payload: Donut): Observable<Donut> {
    return this.http.post<Donut>('/api/donuts', payload)
      .pipe(
        tap((donut) => {
          // use donut instead of payload, because donut has the new id
          // generated by JSON server to db.json
          this.donuts = [...this.donuts, donut];
        }),
        catchError(this.handleError)
    );
  }

  updateDonut(payload: Donut): Observable<Donut> {
    return this.http.put<Donut>(`/api/donuts/${payload.id}`, payload)
      .pipe(
        tap((donut) => {
          this.donuts = this.donuts.map(item => item.id === donut.id ? donut : item);
        }),
        catchError(this.handleError)
      );
  }

  deleteDonut(payload: Donut): Observable<Donut> {
    return this.http.delete<Donut>(`/api/donuts/${payload.id}`)
      .pipe(
        tap(() => {
          this.donuts = this.donuts.filter(donut => donut.id !== payload.id);
        }),
        catchError(this.handleError)
    );
  }
  
  private handleError(err: HttpErrorResponse) {
    if(err.error instanceof ErrorEvent) {
      //client side error/angular application that is causing error
      console.warn('Client', err.message);
    }
    else {
      // server side
      console.warn('Server', err.message);
    }
    return throwError(() => new Error(err.message));
  }
}
