import { inject, Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { map, Observable, of, tap } from 'rxjs';
import { Donut } from '../models/donut.model';

@Injectable({
  providedIn: 'root',
})
export class DonutService {
  private donuts: Donut[] = [];
  private http: HttpClient = inject(HttpClient);

  getDonuts(): Observable<Donut[]> {
    // If there's already data can just return 
    // the loaded donuts list instead of recalling http request.
    if(this.donuts.length) {
      return of(this.donuts);
    }
    return this.http.get<Donut[]>(`/api/donuts`)
      .pipe(tap(donuts => this.donuts = donuts));
  }

  getDonut(id: string): Observable<Donut> {
    return this.getDonuts()
      .pipe(
        map(donuts => {
          const donut = donuts.find(donut => donut.id === id);
          return donut ? donut : {name: '', icon: '', price: 0, description: ''};   
        })
      );
  }

  createDonut(payload: Donut): Observable<Donut> {
    return this.http.post<Donut>('/api/donuts', payload)
      .pipe(tap((donut) => {
        // use donut instead of payload, because donut has the new id
        // generated by JSON server to db.json
        this.donuts = [...this.donuts, donut];
      }));
  }

  updateDonut(payload: Donut): void {
    this.donuts = this.donuts.map(donut => donut.id === payload.id ? payload : donut);
    console.log('this.donuts after update: ', this.donuts);
  }

  deleteDonut(payload: Donut): void {
    this.donuts = this.donuts.filter(donut => donut.id !== payload.id);
    console.log('this.donuts after delete: ', this.donuts);
  }
}
